### ISSUE TITLE
refaktorere fdk-rss-atom-feed til å hente data fra ny fdk-search-service

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-rss-atom-feed#31]
## Parametre i dag
For øyeblikket tilgjengelige søkeparametre:
```python
AVAILABLE_SEARCH_PARAMETERS = (
    "q",
    "losTheme",
    "theme",
    "opendata",
    "accessrights",
    "orgPath",
    "spatial",
    "provenance",
)
```

## Omskriving
Mapping fra tilgjengelige søkeparametre til nøkler i søkeobjekt til ElasticSearch
| fdk-rss-atom-feed | elasticsearch-felt |
| ------------- | ------------- |
| q | query |
| losTheme | losTheme |
| theme | dataTheme |
| opendata | isOpenData |
| accessrights | accessRights |
| orgPath | organization.orgPath |
| spatial | spatial |
| provenance | provenance |

## Endepunkt
Må spørre mot riktig i endepunkt til fdk-search-service
```
datasets
```
## Andre ressurser
Mindre viktig. Vurder å returnere 501 Not Implemented:
Må kanskje gjøres i ingressen.
```
concepts
data-services
information-models
services
events
```

**Comment by terjesyl** [comment]
Setter foreløpig på pause til fordel for andre prioriterte oppgaver. Var en større oppgave å oppgradere til Elasticsearch 8 og legge til auth enn først forutsett @KjerstiSteien

**Comment by terjesyl** [comment]
Tatt opp igjen denne, skriver om til å gjøre spørringer til search-service. Mye på plass, men integrasjonen mot fdk-search-service må fullføres og sjekkes. Og gjerne få på plass noen flere integrasjons og ev. kontraktstester.

**Comment by terjesyl** [comment]
Løst av https://github.com/Informasjonsforvaltning/fdk-rss-atom-feed/pull/35
